apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 3
  selector: #Deployment objects do not create pods themselves but ask master to do it with the given template. The selector is needed so that the deployment object knows which pods belong to it.
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web # yup, used above.
    spec:
      containers:
        - name: client
          image: stephengrider/multi-client
          ports:
            - containerPort: 3000
